// Code generated by MockGen. DO NOT EDIT.
// Source: dispatcher.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLiner is a mock of Liner interface.
type MockLiner struct {
	ctrl     *gomock.Controller
	recorder *MockLinerMockRecorder
}

// MockLinerMockRecorder is the mock recorder for MockLiner.
type MockLinerMockRecorder struct {
	mock *MockLiner
}

// NewMockLiner creates a new mock instance.
func NewMockLiner(ctrl *gomock.Controller) *MockLiner {
	mock := &MockLiner{ctrl: ctrl}
	mock.recorder = &MockLinerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLiner) EXPECT() *MockLinerMockRecorder {
	return m.recorder
}

// Readline mocks base method.
func (m *MockLiner) Readline() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Readline")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Readline indicates an expected call of Readline.
func (mr *MockLinerMockRecorder) Readline() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Readline", reflect.TypeOf((*MockLiner)(nil).Readline))
}

// Stderr mocks base method.
func (m *MockLiner) Stderr() io.Writer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stderr")
	ret0, _ := ret[0].(io.Writer)
	return ret0
}

// Stderr indicates an expected call of Stderr.
func (mr *MockLinerMockRecorder) Stderr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stderr", reflect.TypeOf((*MockLiner)(nil).Stderr))
}

// Stdout mocks base method.
func (m *MockLiner) Stdout() io.Writer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stdout")
	ret0, _ := ret[0].(io.Writer)
	return ret0
}

// Stdout indicates an expected call of Stdout.
func (mr *MockLinerMockRecorder) Stdout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stdout", reflect.TypeOf((*MockLiner)(nil).Stdout))
}

// MockShell is a mock of Shell interface.
type MockShell struct {
	ctrl     *gomock.Controller
	recorder *MockShellMockRecorder
}

// MockShellMockRecorder is the mock recorder for MockShell.
type MockShellMockRecorder struct {
	mock *MockShell
}

// NewMockShell creates a new mock instance.
func NewMockShell(ctrl *gomock.Controller) *MockShell {
	mock := &MockShell{ctrl: ctrl}
	mock.recorder = &MockShellMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShell) EXPECT() *MockShellMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockShell) Check(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockShellMockRecorder) Check(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockShell)(nil).Check), name)
}

// Exec mocks base method.
func (m *MockShell) Exec(ctx context.Context, key string, args ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, key}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Exec indicates an expected call of Exec.
func (mr *MockShellMockRecorder) Exec(ctx, key interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, key}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockShell)(nil).Exec), varargs...)
}

// ExecExternalProgram mocks base method.
func (m *MockShell) ExecExternalProgram(ctx context.Context, name string, args ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecExternalProgram", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecExternalProgram indicates an expected call of ExecExternalProgram.
func (mr *MockShellMockRecorder) ExecExternalProgram(ctx, name interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecExternalProgram", reflect.TypeOf((*MockShell)(nil).ExecExternalProgram), varargs...)
}

// SetStderr mocks base method.
func (m *MockShell) SetStderr(stderr io.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStderr", stderr)
}

// SetStderr indicates an expected call of SetStderr.
func (mr *MockShellMockRecorder) SetStderr(stderr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStderr", reflect.TypeOf((*MockShell)(nil).SetStderr), stderr)
}

// SetStdout mocks base method.
func (m *MockShell) SetStdout(stdout io.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStdout", stdout)
}

// SetStdout indicates an expected call of SetStdout.
func (mr *MockShellMockRecorder) SetStdout(stdout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStdout", reflect.TypeOf((*MockShell)(nil).SetStdout), stdout)
}
